- hosts: local
  user: ace
  become: yes
  roles: 
    - common
    - golang
    - python
    - vagrant
    - nodejs
    - vscode
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Sudo password"
      private: yes