- name: nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Node.js
  shell: '. {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ nodejs_version }}'
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ nodejs_version }}"
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/bash