- name: Add Nodesource apt key.
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: "68576280"
    state: present

- name: Add NodeSource repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"


- name: Update cache and install nodejs
  apt: 
    pkg: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    update_cache: yes