- name: Installs base packages
  apt: pkg="{{ item }}" state=latest update_cache=yes
  with_items:
    - curl
    - git

- name: Installs vagrant
  apt: deb=https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb

